name: Primo DIY Documentation
pygments: true
markdown: kramdown
#baseurl: http://docs.primo.io/
baseurl: "prototype-documentation"
#baseurl: http://tatianeforster.github.io/

theme: jekyll-theme-minimal